runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /stylesheet
  static_dir: static
- url: /images
  static_dir: myimgs
- url: /.*
  script: main.app
